# Generated by Django 4.1.3 on 2024-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
